language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist

cache:
    directories:
        - $HOME/.composer/cache

notifications:
  email: false